services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: DP.mysqlreact.1218
      MSQL_DATABASE: space_tracker
      MYSQL_USER: root
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-networks

  app: 
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL:  db://root:DP.mysqlreact.1218@db:3306/space-tracker
      DB_HOST: localhost
      DB_PORT: "3306"
      DB_USER: root
      DB_PASS: DP.mysqlreact.1218
      DB_NAME: space_tracker

      URL_USER: danpittari@gmail.com
      URL_PASS: Spacetracker_1218
      
    depends_on:
      - db

    networks:
      - app-networks

volumes:
  mysql-data:

networks:
  app-networks: